### PR TITLE
Implement fix to ROME update equation from R-ROME

### PR DESCRIPTION
**Pull request by sidnb13**
See details here: [https://github.com/scalable-model-editing/rebuilding-rome](https://github.com/scalable-model-editing/rebuilding-rome). This simple fix unifies the key vector computation in the ROME update, mitigating model collapse & enabling sequential editing at larger scale.

### CODE REVIEW

**Comment by pengzju** [comment]
Thank you for your valuable contribution to our repository! Your PR, which addresses the key vector computation in the ROME update, is a significant step towards mitigating model collapse and enabling more efficient large-scale sequential editing. We appreciate the effort and are happy to integrate your improvements. 😊

**Comment by akshat57** [comment]
Hi,

Currently we merged r-ROME into the original implementation of ROME. However, would you prefer them to be separate and r-rome be another model?

**Comment by pengzju** [comment]
I temporarily withdraw this PR. I will update the new method and rename it to `r-rome` in the future. Thank you very much for your contribution.

**Comment by akshat57** [comment]
For sure. Thank you!

**Pull request merged**
